Project_KAJ/Project_KAJ/urls.py
from django.contrib import admin
from django.urls import path,include
import main.views
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', main.views.home, name ='home'),
    path('accounts/',include('accounts.urls')),
    path('main/',include('main.urls')),
    path('seeun/',main.views.seeun, name ='seeun'),
]

Project_KAJ/UNIV/urls.py
from django.contrib import admin
from django.urls import path
from . import views


urlpatterns = [
  
]

Project_KAJ/accounts/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'accounts'


urlpatterns = [
    path('signup/',views.signup,name='signup'),
    path('login/',views.login,name='login'),
    path('logout/',views.logout,name='logout'),
]

Project_KAJ/main/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

# app_name = 'main'

urlpatterns = [
    path('', views.home, name="home"),
    path('<int:blog_id>', views.detail, name="detail"),
    path('create', views.create, name="create"),
    path('update/<int:blog_id>', views.update, name="update"),
    path('edit/<int:blog_id>', views.edit, name="edit"),
    path('new', views.new, name="new"),
    path('delete/<int:blog_id>', views.delete, name="delete"),
    path('seeun/', views.seeun, name="seeun"),
    path('seyeon', views.seyeon, name="seyeon"),
]

Project_KAJ/UNIV/models.py
from django.db import models

Project_KAJ/accounts/models.py
from django.db import models

# Create your models here.

Project_KAJ/main/models.py
from django.db import models
# Create your models here.

class Blog(models.Model):
    title = models.CharField(max_length=200)
    pub_date = models.DateTimeField()
    body = models.TextField()

    def __str__(self):
        return self.title

    def summary(self):
        return self.body[:100]

Project_KAJ/UNIV/views.py
from django.shortcuts import render,get_object_or_404, redirect
# Create your views here.

Project_KAJ/accounts/views.py
from django.shortcuts import render,redirect
from django.contrib import auth
from django.contrib.auth.models import User
# Create your views here.

def signup(request):
    if request.method == 'POST':
        # User has info and wants an account now!
        if request.POST['password1'] == request.POST['password2']:   
            try:
                user = User.objects.get(username=request.POST['username'])
                return render(request, 'signup.html', {'error': 'Username has already been taken'})
            except User.DoesNotExist:
                user = User.objects.create_user(
                    request.POST['username'], password=request.POST['password1'])
                auth.login(request, user)   #로그인 상태를 유지시켜주는 함수임
               

                return redirect('accounts:login')
        else:
            return render(request, 'accounts/signup.html', {'error': 'Passwords must match'})
    else:
        # User wants to enter info
        return render(request, 'signup.html')
    return render(request, 'home.html')

def login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = auth.authenticate(request, username=username, password=password)
        if user is not None:   #유저가 none 이 아니면은 로그인 조져라  그다음에 홈창으로 가주는거임
            auth.login(request, user)
            return redirect('home')
        else:
            return render(request, 'accounts/login.html', {'error': 'username or password is incorrect.'})
    else:
        return render(request, 'login.html')
        
def logout(request):
    auth.logout(request)
    return redirect('home')          #그냥 단순하게 로그아웃 상태가 해체된다

Project_KAJ/main/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from .models import Blog
from .form import BlogForm
# Create your views here.


def create(request, blog_id):
    update_blog = get_object_or_404(Blog, pk=blog_id)
    update_blog.title = request.POST['title']
    update_blog.pub_date = timezone.datetime.now()
    update_blog.body = request.POST['body']
    update_blog.save()
    return redirect('detail', update_blog.id)


def home(request):
    blogs = Blog.objects.all()
    return render(request, 'home.html', {'blogs': blogs})


def detail(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'detail.html', {'blog': blog})


def new(request):
    if request.method == 'POST':
        form = BlogForm(request.POST, request.FILES)
        if form.is_valid():
            content = form.save(commit=False)
            content.pub_date = timezone.now()
            content.save()
            return redirect('home')
    else:
        form = BlogForm()
        return render(request, 'new.html', {'form': form})


def update(request, blog_id):
    update_blog = get_object_or_404(Blog, pk=blog_id)
    update_blog.title = request.POST['title']
    update_blog.pub_date = timezone.datetime.now()
    update_blog.body = request.POST['body']
    update_blog.save()
    return render('detail', update_blog.id)


def create(request):
    new_blog = Blog()
    new_blog.title = request.POST['title']
    new_blog.pub_date = timezone.datetime.now()
    new_blog.body = request.POST['body']
    new_blog.save()
    return redirect('/main/'+str(new_blog.id))


def edit(request, blog_id):
    edit_blog = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'edit.html', {'blog': edit_blog})


def delete(request, blog_id):
    delete_blog = get_object_or_404(Blog, pk=blog_id)
    delete_blog.delete()
    return redirect('home')


def seeun(request):
    return render(request, 'seeun.html')

def seyeon(request):
    return render(request, 'seyeon.html')

Project_KAJ/Project_KAJ/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>알콜타임</title>

    <style>
        @font-face {
            font-family: 'RIDIBatang';
            src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_twelve@1.0/RIDIBatang.woff') format('woff');
            font-weight: normal;
            font-style: normal;
        }

        a {
            font-family: 'RIDIBatang';
        }
        div {
            font-family: 'RIDIBatang';
        }
        button {
            font-family: 'RIDIBatang';
        }
    </style>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

<body>
    <nav class="navbar navbar-expand-sm navbar-light bg-success">
        <!-- <ul class="navbar-nav"> -->
        <a class="navbar-brand" href="{% url 'home' %} " style="color: white; font-weight: 800;">
            김앤장(KIM AND CHANG)</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                {% if not user.is_authenticated %}
                <!-- 유저 로그인 상태확인해주는거임-->
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'accounts:signup' %}" style="color: white;">회원가입 <span
                            class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'accounts:login' %}">로그인 <span class="sr-only">(current)</span></a>
                </li>

                {% else %}
                <!-- 만약에 로그인 되면은 로그인만뜨고-->
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'accounts:logout' %}">로그아웃하렴 <span
                            class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="#">나의 페이지 <span class="sr-only">(current)</span></a>
                </li>
                {% endif %}
                <!-- 로그아웃 안되게 하면 뭐 하나만뜨게해주는거임-->
                <!-- <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                </li> -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        술술술
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="#">술자리 예절</a>
                        <a class="dropdown-item" href="#">술게임</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">술자리 금기</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        커뮤니티
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'seeun' %} ">지역별 술 종류(추천)</a>
                        <a class="dropdown-item" href="{% url 'seyeon' %}">나의 술자리 썰</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">술 순위&후기</a>
                    </div>
                </li>
                <!-- <li class="nav-item">
                    <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                </li> -->
            </ul>
            <!-- <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form> -->
        </div>
    </nav>







    {% block content %}
    {% endblock %}



    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>

    <br><br><br><br><br><br><br><br><br><br>

    <!-- Footer -->
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white"> Copyright &copy; Project Goorm 2020 </p>

            <p class="m-0 text-right text-white"> <a href="#">Developer</a>></p>


        </div>
        <!-- /.container -->
    </footer>
</body>

</html>

Project_KAJ/accounts/templates/login.html
{% extends 'base.html' %}
{% block content %}
<div class="div" >
  <form method="POST" action="{% url 'accounts:login'%}">
    {% csrf_token %}
    <br>
    아이디:<input type="text" name="username" required="required" placeholder="Your id"><br><br>

    비밀번호:<input type="password" name="password" required="required" placeholder="Your password"><br><br>

    <input type="submit" value="Sign in"><br><br><br>
    <a href="{% url 'accounts:signup' %}">회원가입쳐라</a>

  </form>
</div>

{% endblock %}

Project_KAJ/accounts/templates/signup.html
{% extends 'base.html' %}
{% block content %}

<form method="POST" action="{% url 'accounts:signup' %}">
    {% csrf_token %}

    아이디: <input type="text" name="username" required="required" placeholder="Your id"><br><br><br>
    패스워드:<input type="password" name="password1" required="required" placeholder="Your password"><br><br><br>
    confirm ps:<input type="password" name="password2" required="required" placeholder="Your password"><br><br><br>
    <label for="password">너의 비밀번호야 ^^</label>

    <input type="submit" value="Sign Up!">


</form>


{% endblock %}

Project_KAJ/main/templates/detail.html
{% extends 'base.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Detail</title>
</head>

<body>
    <h1>Detail page</h1>
    <h3>제목:{{blog.title}}</h3>
    <hr>
    <p>{{blog.pub_date}}</p>
    <p>{{blog.body}}</p>
    <a href="{%url 'home'%}">home</a>
    <a href="{%url 'delete' blog.id %}">삭제하기</a>
    <a href="{%url 'edit' blog.id %}">수정하기</a>
</body>

</html>
{% endblock %}

Project_KAJ/main/templates/edit.html
{% extends 'base.html' %}
{% block content %}

<h1>글 수정하기</h1>

<form action="{%url 'update' blog.id %}" method="POST">
    {%csrf_token%}
    제목:<input type="text" value="{{blog.title}}" name="title">
    <br>
    <br>
    본문: <textarea name="body" id="" cols="30" rows="10">{{blog.body}}</textarea>
    <br>
    <button type="submit">작성!</button>

</form>

{% endblock %}

Project_KAJ/main/templates/home.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Page Title</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='stylesheet' type='text/css' media='screen' href='main.css'>
    <script src='main.js'></script>
    <style>
        a:link {color: black}
        body {
        background-color: beige;}
    </style>
</head>
<body>
    <div id="demo" class="carousel slide" data-ride="carousel">
        
        <!-- The slideshow -->
        <div class="carousel-inner" style="text-align: center;">
          <div class="carousel-item active" >
            <img src="{% static '술자리.jpg'%}" alt="Los Angeles" width="500" height="auto">
          </div>
          <div class="carousel-item">
            <img src="{% static '술자리예절.jpg'%}" alt="Chicago" width="265" height="auto">
          </div>
          <div class="carousel-item">
            <img src="{% static '술자리.jpg'%}" alt="New York" width="500" height="auto">
          </div>
        </div>
        
        <!-- Left and right controls -->
        <a class="carousel-control-prev" href="#demo" data-slide="prev" >
          <span class="carousel-control-prev-icon"></span>
        </a>
        <a class="carousel-control-next" href="#demo" data-slide="next">
          <span class="carousel-control-next-icon"></span>
        </a>
      </div>
          


        <a href="{%url 'new' %}" style="color: black">새글 작성하기</a>
  
{% for blog in blogs%}


<hr>
<div style="text-align: center;">
<a href="{%url 'detail' blog.id%}">
{{blog.title}}
<br>
{{blog.pub_date}}
<br>
{{blog.summary}}
</a>
</div>


{% endfor %}
{% endblock %}

</body>
</html>

Project_KAJ/main/templates/new.html
{% load static %}
<h1>새 글 작성하기</h1>
<form method='POST' enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {{form.as_table}}
    </table>
    
    <input class= "btn btn-dark" type="submit" value="저장">

</form>

Project_KAJ/main/templates/seeun.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1><지역별 술 종류></h1><hr>
   <div>
       <img src="{% static '강원도.png'%}" alt="Los Angeles" width="170" height="auto">
       강원도 술
   </div> <br>
   <div>
    <img src="{% static '전라북도.png'%}" alt="Los Angeles" width="170" height="230">
    전라북도 술
</div><br>
<div>
    <img src="{% static '충청남도.png'%}" alt="Los Angeles" width="200" height="auto">
    충청남도 술
</div>
{% endblock %}

</body>
</html>

Project_KAJ/main/templates/seyeon.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>sul talk</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
</head>

<body style="text-align:center">
    <h1>
        <나의 술자리이야기>
    </h1>
    <hr>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-3 col-md-6 alert-warning">
                (익명)<br>
                저는 술자리에서 안주를 먹었어요
            </div>
            <div class="col-sm-9 col-md-6 bg-warning">
                (익명)<br>
                저는 술먹고 지하철타고 집왔어요
            </div>
        </div>
    </div>
</body>

</html>

{% endblock %}